version: '3.7'
services:

  init:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command: 
      - composer
      - init

  require:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command:
      - composer
      - require
      - solarium/solarium:6.2.4

  install:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command:
      - composer
      - install