version: '3.7'
services:

  init:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command: 
      - composer
      - init

  require:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command:
      - composer
      - require
      - symfony/event-dispatcher

  install:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command:
      - composer
      - install

  autoload:
    image: composer:2.3.7
    volumes:
      - ./:/app:consistent
    command:
      - composer
      - dumpautoload